"""init

Revision ID: b0cf5a59e3a5
Revises: 
Create Date: 2021-06-02 19:06:06.681722

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b0cf5a59e3a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'currency',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('password', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'wallet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('currency_id', sa.Integer(), nullable=True),
        sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ['currency_id'],
            ['currency.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'transfer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_wallet_id', sa.Integer(), nullable=True),
        sa.Column('target_wallet_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            'event_time',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['from_wallet_id'],
            ['wallet.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_wallet_id'],
            ['wallet.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
